config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  resources :users ,except: [:new] do
    member do
    	get 'profile' 
    	get 'matches'
    end
  end
  match "sign_out", to: "sessions#destroy" ,via: 'delete'
  get 'auth/facebook/callback' ,to: "sessions#create"

  post 'create_friendship' => 'friendships#create'

  delete 'delete_friendship' => 'friendships#destroy'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    can :update , User do |u|
      u == user
    end

    can :read , User do |u|
      u == user
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

	before_validation :generate_uuid

  def generate_uuid
    #generate_unique_field! :propertyid, 6 if propertyid.blank?
    #raise RuntimeError, "testing exception handling in production"
    self.uuid = RandomToken.genf(10,c: :d) if self.uuid.blank? || self.new_record?
  end
	belongs_to :user
	belongs_to :friend , class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship" , foreign_key: "friend_id",dependent: :destroy

  has_attached_file :avatar,
    :styles => {:medium => "370x370", :thumb => "100x100"},
    :storage => :s3,
    :path => ":class/:id/:style/:filename",
    :url => ':s3_domain_url'


  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


  def self.sign_in_from_facebook(auth)
    find_by(provider: auth['provider'] , uid: auth['uid']) || create_user_from_facebook(auth)
  end

  def self.create_user_from_facebook(auth)

    create ( {
               avatar: process_uri(auth['info'][:image] + "?width=999999"),
               email: auth[:info][:email],
               provider: auth['provider'],
               uid: auth['uid'],
               name: auth['info'][:name],
               gender: auth[:extra][:raw_info][:gender],
               date_of_birth:  auth[:extra][:raw_info][:age_range][:min],
               location: auth[:info][:location],
               bio: auth[:extra][:raw_info][:bio]
    })
  end

  def request_match(user2)
    self.friendships.create(friend: user2)

  end

  def accept_match(user2)
    self.friendships.where(friend: user2).first.update_attribute(:state, "ACTIVE")
  end

  def remove_match(user2)
    inverse_friendship = inverse_friendships.where(user_id: user2).first

    if inverse_friendship
      self.inverse_friendships.where(user_id: user2).first.destroy
    else
      self.friendships.where(friend_id: user2).first.destroy
    end
  end

  #filter methods
  def self.gender(user)
    case user.interest
    when "Male"
      where('gender = ?', 'male')
    when "Female"
      where('gender = ?', 'female')
    else
      all
    end


  end

  def self.not_me(user)
    where.not(id: user.id)
  end

  def matches(current_user)
    friendships.where(state: "pending").map(&:friend) + current_user.friendships.where(state: "ACTIVE").map(&:friend) + current_user.inverse_friendships.where(state: "ACTIVE").map(&:user) 
  end

  def find_friendship(current_user, user)
    Friendship.where(user_id: current_user.id, friend_id: user.id).first ||  Friendship.where(user_id: user.id, friend_id: current_user.id).first
  end
  private
  def self.process_uri(uri)
    avatar_url = URI.parse(uri)
    avatar_url.scheme = 'https'
    avatar_url.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to users_path

  end
  private
  def current_user
    
    @current_user ||= User.find(session[:user_id]) if session[:user_id]


  end
  def require_login
    if session[:user_id] == nil
      redirect_to root_path, notice: "Please Login"
    end
  end
  helper_method :current_user, :require_login
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :require_login ,:set_friend

  def create
    @inverse_friendship = current_user.inverse_friendships.where(user_id: @friend.id)

    unless @inverse_friendship.blank?
      @friend.accept_match(current_user)
      @match = true
    else
      current_user.request_match(@friend)
    end

    respond_to do |format|
      format.js
    end

  end

  def destroy
    current_user.remove_match(@friend)

    respond_to do |format|
      format.html{ redirect_to users_path}
    end
  end

  private
  def set_friend
    @friend = User.find(params[:friend_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	if current_user
  		redirect_to users_path
  	end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth
    user = User.sign_in_from_facebook(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "signed in"
  end

  def destroy
    session[:user_id] = nil
    session[:omniauth] = nil
    session.delete(:user_id)
    user = nil
    redirect_to root_url, notice: "signed out"


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, :set_user, only: [:edit, :profile, :update, :destroy,:matches]
  def index
    if params[:id]
      @users = User.gender(current_user).not_me(current_user).where('id < ?', params[:id]).limit(10) - current_user.matches(current_user)
    else
      @users = User.gender(current_user).not_me(current_user).limit(10) - current_user.matches(current_user)
    end
    respond_to  do |format|
      format.html
      format.js
    end
  end

  def edit
    authorize! :update, @user

  end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path(@user)

    else
      redirect_to edit_user_path(@user)
    end

  end

  def destroy
    if @user.destroy
      session[:user_id] = nil
      session[:omniauth] = nil
      redirect_to root_path

    else
      redirect_to edit_user_path(@user)
    end
  end

  def matches
    authorize! :read, @user
    @matches = current_user.friendships.where(state: "ACTIVE").map(&:friend) + current_user.inverse_friendships.where(state: "ACTIVE").map(&:user)

  end

  def profile
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:interest,:bio,:avatar, :location, :date_of_birth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def name(user)
    if user.name
      case user
      when user
        user.name.partition(' ').first
      when @user
        user.name.partition(' ').first
      end
    end
  end
  def age(user)
    if user.date_of_birth
      user.date_of_birth.to_s + " yrs +"
    end
  end
  def location(user)
    if user.location
      case user
      when user
        user.location.partition(',').first
      when @user
        user.location.partition(',').first
      end
    end
  end
  def bio(user)
    unless user.bio.blank?
    	user.bio
    else
    	"this user did not fill out their bio yet".humanize
    end
  end

end

app/views/friendships/create.js.erb
<% if @match == true %>
swal({
	type: "success",
	title: "<span>You've got a match!</span>",
	text: '<div class="match"><img src= "<%= @friend.avatar %></div>"  >',
	confirmButtonText: "Ok",
	html: true


})

<% end %>

app/views/home/index.html.erb
<div class="bg-dark"></div>

<div class="home-information">
	
	<h1 class="slogan text-capitalize">Any swipe can change your life</h1>

	<%= link_to "auth/facebook" , class:"btn btn-lg btn-facebook btn-social" do %>
		<i class="fa fa-facebook">   </i>   Sign In with Facebook

	<% end %>
	<br>
</div>

<script type="text/javascript">


$(function() {
    $('body').vegas({
    		timer:false,
    		shuffle: true,
    		preload: true,
                delay: 4000,
    transitionDuration: 2000,
              transition: 'blur2',
        slides: [
            { src: '<%= asset_path("bg2_min.jpg") %>' },
            { src: '<%= asset_path("bg_min.jpg") %>' }
        ]
    });
});
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<% if current_user %>

<nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">
	<%= render 'layouts/navigation_links' %>
</nav>
<div class="navbar navbar-default navbar-fixed-top">

	  <button type="button" class="navbar-toggle button-nav" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="body">
		  	<i class="fa fa-cog"></i>
		  </button>

		<div class="">

		  <%= link_to root_path, class: "navbar-brand" do %>
		<h2 class="logo">Matchr</h2>
		  <% end %>
		  	</div>


		  <button type="button" class="navbar-toggle button-nav pull-right">
		  	<%= link_to matches_user_path(current_user) do %><i class="fa fa-heart"></i><% end %>
		  </button>

	
</div>

	<% else %>


		<div class="navbar-brand">
		<h1 class="logo-outside">Matchr</h1>
	</div>

	<% end %>

app/views/layouts/_navigation_links.html.erb
		<ul class="nav navmenu-nav">
			<li class="<%= if params[:action] == "index" then "active" end %> nav-btn">
				<%= link_to root_path do %><i class="fa fa-users"></i> Discover <% end %>
			</li>

			<li class="<%= if params[:action] == "matches" then "active" end %> nav-btn">
				<%= link_to matches_user_path(current_user) do %><i class="fa fa-heart"></i> Matches <% end %>
			</li>

			<li class="<%= if params[:action] == "edit" then "active" end %> nav-btn">
				<%= link_to edit_user_path(current_user) do %><i class="fa fa-cog"></i> Settings <% end %>
			</li>

			<li class="nav-btn"><%= link_to '/sign_out', method: :delete do %><i class="fa fa-cog"></i> Log out <% end %></li>

		</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Matchr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Matchr" %>">
    <link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
      <link href='https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.0/sweetalert.min.css' rel='stylesheet' type='text/css'>
  <script src="https://cdn.firebase.com/js/client/2.2.9/firebase.js"></script>


    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.0/sweetalert.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <header>
      <%= render 'layouts/navigation' %>
    </header> 
    <div >
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
  </body>
</html>

app/views/users/_user.html.erb
<li id= "<%= user.id %>" class="profile-box">
	<div class="img"> <%= image_tag user.avatar.url(:medium), height:"100%" ,width: "370" %>	</div>
	<div class="user-name pull-left">
		<%= link_to profile_user_path(user.id) ,class:"" do %>
		<%= name(user) %>   <%= age(user) %> 
		<% end %>
	</div>
	<div class="user-location text-right">
		<i class="fa fa-map-marker"></i> <%= location(user) %>
	</div>
	<%= link_to "", create_friendship_path(friend_id: user.id) , id: "user_#{user.id}",method: :post, remote: true %>
</li>

app/views/users/edit.html.erb
<%=simple_form_for(@user,url: url_for(:action => "update",:controller => "users"),html:{multipart: true}) do |f| %>

<div class="container">
	<h4 class="text-uppercase"><small>interested in</small></h4>
	<div class="dropdown">
		<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		<%= @user.interest.capitalize %>
		<span class="caret"></span>
		</button>
		<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			<li class="gender"><a href="#">Female</a></li>
			<li class="gender"><a href="#">Male</a></li>

		</ul>
	</div>

	<%= f.input :interest, as: :hidden, label: false %>


	<h4 class="text-uppercase"><small>Profile Description </small></h4>
	<%= f.input :bio, as: :text,  label: false, :input_html => {:rows => 5 ,class: "form-control"} %>

	<h4 class="text-uppercase"><small>City </small></h4>
	<%= f.input :location,  label: false ,:input_html => {class: "form-control"} %>

	<h4 class="text-uppercase"><small>Age </small></h4>
	<%= f.input :date_of_birth, as: :string,  label: false,:input_html => {class: "form-control"}  %>
	<br>
	<div class="center-block">
	<div class="fileinput fileinput-new " data-provides="fileinput">
		<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
		<img src="<%= @user.avatar %>">
		</div>
		<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
		<div>
			<span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
			<%= f.file_field :avatar, label: false %>

			</span>
			<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
		</div>
	</div>
</div>

<%= f.button "submit", class: "btn btn-success btn-block",value: "submit" %>

<br>


		<%= link_to 'Cancel Your Account'.html_safe,  user_path(current_user.id), method: "delete", data: {
			toggle: "tooltip" ,placement: "top",
    confirm: 'Are you sure you want to delete your account?',
    :'confirm-button-text' => 'Yes',
    :'cancel-button-text' => 'No',
    type: 'error',
    text: "This Can't Be Undone!",
    }  ,title: "Delete Account" %>

</div>

<% end %>

<script type="text/javascript">
	$(".gender").click(function(){
		$("#dropdownMenu1").text($(this).text())
				$("#dropdownMenu1").append('<span class="caret"></span>')
				$('#user_interest').val($(this).text());

	})

</script>

app/views/users/index.html.erb
<div class="container">
	<br>

<div class="row">
<div class="text-center">
<div class="wrap">

	<div id="tinderslide">
	    <ul>
	    	<%= render @users %>
	    </ul>
	</div>


        <div class="actions">
            <a href="#" class="dislike"><i class="fa fa-times"></i></a>
            <a href="#" class="like"><i class="fa fa-heart"></i></a>
        </div>



</div>
</div>
</div>
</div>

<div class="spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>

app/views/users/index.js.erb
$("#tinderslide ul").append('<%= j render :partial => @users,:collection => @users %>')
	$('#tinderslide > ul li').tinysort({attr: "id"})

$('#tinderslide').jTinder();

app/views/users/matches.html.erb
<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th></th>
				<th>Name</th>
				<th>Matched On</th>
				<th></th>
			</tr>
		</thead>
		<tbody>


    <% @matches.each do |match| %>
      <tr>
  <th> <%= image_tag("#{match.avatar(:thumb)}",size: "50x50" ) %></th>
  <td><%= link_to(match.name, profile_user_path(match.id),class: "match-name" ) %></td>
  <td><%= match.updated_at.strftime('%m/%d/%y') %></td>

  <td> <%= match.find_friendship(current_user, match).uuid %></td>
  <td class="text-right">
    
    <button class="chatbtn btn btn-xs btn-info " data-toggle="tooltip" id="<%= match.find_friendship(current_user,match).uuid %>" data-placement="top" title="Chat"><i class="fa fa-envelope"></i></button>




    <%= link_to '<i class="fa fa-times"></i>'.html_safe,  delete_friendship_path(friend_id: match.id),class:"btn btn-danger btn-xs", method: "delete", data: {
      toggle: "tooltip" ,placement: "top",
    confirm: 'Are you sure you want to unmatch?',
    :'confirm-button-text' => 'Yes',
    :'cancel-button-text' => 'No',
    type: 'error',
    text: "you should try anything atleast once.. ;)",
    }  ,title: "Unmatch" %>
  </td>
</tr>

    <% end %>
		
		</tbody>

	</table>

</div>




<div class="row addwindow">
</div>


<script type="text/javascript">
	
		$(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })


    //$('.example-chat').hide();
$(document).ready(function() {

    var firebaseid, messagesRef, dataId;

    $('.chatbtn').click(function(e) {

        $(this).addClass('disabled')
        //firebaseid = null
        firebaseid = $(this).attr('id');
        initFirebase(firebaseid)

    })



    function initFirebase(firebaseid) {
        messagesRef = new Firebase('https://matchr.firebaseio.com/matches/' + firebaseid);
        initChatWindow(messagesRef)
        checkInput();
    
      }

      function checkInput(){
      $('.messageInput').click(function(){
       firebaseid = $(this).closest('.l-demo-container').attr('id');
       console.log(" fireing " + firebaseid)
       messagesRef = new Firebase('https://matchr.firebaseio.com/matches/' + firebaseid);

    })
      }

    function initChatWindow(fireBaseRef){

      messagesRef = fireBaseRef

      var msgWindow = '<div class="example-chat l-demo-container " id ="'+ firebaseid +'"><ul id="example-messages"' + 'data-id =' + firebaseid + ' class="example-chat-messages"></ul> <footer> <input type="text" id="messageInput" class="messageInput" placeholder="Type a message..."> </footer></div>'
        

    


        if (dataId != firebaseid) { 

         $('.addwindow').prepend(msgWindow);
       }
        

        dataId = $('#example-messages').data('id')
        console.log(dataId)

        var messageList = $('ul').filter(function() {
            return $(this).attr('data-id') === firebaseid;
        })




        var messageField = $('#messageInput');
        var nameField = $('#nameInput');
        //var messageList = $('#example-messages');



        //  LISTEN FOR KEYPRESS EVENT
        messageField.keypress(function(e) {
            if (e.keyCode == 13) {
                //FIELD VALUES
                var username = "<%= current_user.name %>"
                var message = messageField.val();

                //SAVE DATA TO FIREBASE AND EMPTY FIELD
                messagesRef.push({
                    name: username,
                    text: message
                });
                messageField.val('');
            }
        });

        // Add a callback that is triggered for each chat message.
        messagesRef.limitToLast(10).on('child_added', function(snapshot) {
            //GET DATA
            var data = snapshot.val();
            var username = data.name
            var message = data.text;

            //CREATE ELEMENTS MESSAGE & SANITIZE TEXT
            var messageElement = $("<li class=''>");
            var nameElement = $("<strong class='example-chat-username'></strong>")
            nameElement.text(username);
            messageElement.text(message).prepend(nameElement);

            //ADD MESSAGE
            messageList.append(messageElement)

            //SCROLL TO BOTTOM OF MESSAGE LIST
            messageList[0].scrollTop = messageList[0].scrollHeight;
        });

    }

})
</script>

app/views/users/profile.html.erb
<div class="container">
	<div class="wrap">
		<div class="profile-box">
			<div class="img">
				<%= image_tag("#{@user.avatar(:medium)}",height:"100%",width: "100%") %>
			</div>
			<div class="user-name pull-left  ">
				<%= name(@user) %>  <%= age(@user) %>					</div>

			<div class="user-location  text-right "><i class="fa fa-map"></i> <%= location(@user) %></div>

			<div class="description">
			<h4 class="text-uppercase"><small>description</small></h4>
			<p class="small text-muted">
				<%= bio(@user) %>
			</p>
		</div>
	</div>
</div>